name: Setup Flutter environment
description: This action sets up a Flutter development environment. It installs Java, Flutter, and fetches all the project dependencies.
inputs:
  java-version:
    description: 'The version of Java to be installed. e.g. 17'
    required: true
  flutter-channel:
    description: 'The Flutter channel to use. e.g. stable, beta'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{inputs.java-version}}
        cache: 'gradle'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: ${{inputs.flutter-channel}}
        cache: true

    - name: Disable Dart Analytics
      run: dart --disable-analytics
      shell: bash

    - name: Disable Flutter Analytics
      run: flutter config --disable-analytics
      shell: bash

    - name: Get dependencies
      run: flutter pub get
      shell: bash