name: Setup Flutter environment
description: This action sets up a Flutter development environment. It installs Java, Flutter, and fetches all the project dependencies.
inputs:
  java-version:
    description: 'The version of Java to be installed. e.g. 17'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: 'zulu'
        java-version: ${{inputs.java-version}}
        cache: 'gradle'

    - name: Read Flutter version
      id: read_flutter_version
      run: echo "VERSION=$(cat fastlane/metadata/android/flutter-version.txt)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Setup Flutter
      uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
      with:
        flutter-version: ${{ steps.read_flutter_version.outputs.VERSION }}
        cache: true

    - name: Disable Dart Analytics
      run: dart --disable-analytics
      shell: bash

    - name: Disable Flutter Analytics
      run: flutter config --disable-analytics
      shell: bash

    - name: Get dependencies
      run: flutter pub get
      shell: bash